# Generated by Django 5.2.17 on 2026-09-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('street_address', models.CharField(max_length=200, verbose_name='dirección')),
                ('apartment', models.CharField(blank=True, max_length=100, verbose_name='piso / puerta (opcional)')),
                ('postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='país')),
                ('is_default', models.BooleanField(default=False, verbose_name='dirección predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
