# Generated by Django 5.2.17 on 2026-09-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('story', models.TextField(blank=True, verbose_name='historia')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='logotipo')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('volume', models.CharField(choices=[('250ML', '250 ml'), ('500ML', '500 ml'), ('750ML', '750 ml'), ('1L', '1 L'), ('2L', '2 L'), ('3L', '3 L'), ('5L', '5 L')], max_length=10, verbose_name='volumen')),
                ('origin_region', models.CharField(blank=True, max_length=120, verbose_name='origen / región')),
                ('harvest_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cosecha')),
                ('acidity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='acidez (%)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para ocultar el producto de la tienda sin borrarlo.', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
