# Generated by Django 5.2.17 on 2026-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_year',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='cosecha'),
        ),
    ]
