# Generated by Django 5.2.17 on 2026-09-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_fee', models.DecimalField(decimal_places=2, default=4.95, max_digits=6, verbose_name='gastos de envío (€)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Deja en blanco para no ofrecer envío gratuito.', max_digits=8, null=True, verbose_name='envío gratis a partir de (€)')),
            ],
            options={
                'verbose_name': 'configuración de envío',
                'verbose_name_plural': 'configuración de envío',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de pago'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('shipping_full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('shipping_phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('shipping_street_address', models.CharField(max_length=200, verbose_name='dirección')),
                ('shipping_apartment', models.CharField(blank=True, max_length=100, verbose_name='piso / puerta')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('shipping_province', models.CharField(max_length=100, verbose_name='provincia')),
                ('shipping_country', models.CharField(default='España', max_length=100, verbose_name='país')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('product_volume', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'artículo del pedido',
                'verbose_name_plural': 'artículos del pedido',
            },
        ),
    ]
