# Generated by Django 5.2.17 on 2026-09-09 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='flat_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.95'), max_digits=6, verbose_name='gastos de envío (€)'),
        ),
    ]
