# Generated by Django 5.2.17 on 2026-09-12 16:04, hand-edited: access_token
# needs a per-row unique value, not one default reused for every existing
# row — see https://docs.djangoproject.com/en/5.2/howto/writing-migrations/#migrations-that-add-unique-fields

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_access_tokens(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.filter(access_token__isnull=True).iterator():
        order.access_token = uuid.uuid4()
        if not order.email and order.user_id:
            order.email = order.user.email
        order.save(update_fields=["access_token", "email"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_shippingsettings_flat_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.RunPython(populate_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
