# Generated by Django 5.2.17 on 2026-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_access_token_order_email_order_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('PROCESSING', 'En preparación'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado')], default='PROCESSING', max_length=20, verbose_name='estado de envío'),
        ),
    ]
