# Generated by Django 5.2.17 on 2026-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSING', 'En preparación'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado')], default='RECEIVED', max_length=20, verbose_name='estado de envío'),
        ),
    ]
