# Generated by Django 5.2.17 on 2026-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_local_delivery',
            field=models.BooleanField(default=False, verbose_name='reparto local'),
        ),
        migrations.AddField(
            model_name='order',
            name='local_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de reparto local'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='local_delivery_postal_codes',
            field=models.CharField(blank=True, help_text='Códigos postales con envío gratuito y reparto semanal propio, separados por comas (p. ej. 12001,12002,12003,12004,12005,12006,12100,12530,12540,12550,12560 para Castellón de la Plana, el Grao, Burriana, Vila-real, Almassora y Benicàssim). Deja en blanco para desactivar el reparto local.', max_length=500, verbose_name='códigos postales de reparto local gratuito'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='local_delivery_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana en que se realiza el reparto local. Requiere haber indicado códigos postales.', null=True, verbose_name='día de reparto local'),
        ),
    ]
