# Generated by Django 5.2.17 on 2026-10-03 10:40

import django.db.models.deletion
import orders.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_seed_local_delivery_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='descuento'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Se incluye en el correo al cliente cuando el pedido pasa a «Enviado».', max_length=100, verbose_name='número de seguimiento'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Enlace a la web del transportista para seguir el envío (opcional).', verbose_name='enlace de seguimiento'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Déjalo en blanco para generarlo automáticamente.', max_length=20, unique=True, verbose_name='código')),
                ('email', models.EmailField(help_text='Solo se puede usar en pedidos con este correo.', max_length=254, verbose_name='correo del cliente')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=5, verbose_name='descuento (%)')),
                ('expires_at', models.DateTimeField(default=orders.models._default_discount_expiry, verbose_name='válido hasta')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('issued_for_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_discount_codes', to='orders.order', verbose_name='emitido por el pedido')),
            ],
            options={
                'verbose_name': 'código de descuento',
                'verbose_name_plural': 'códigos de descuento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcode', verbose_name='código de descuento'),
        ),
    ]
